config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :contacts, only: [:new, :create]
  
  root 'home#index'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'contacts#new'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "mark@markmcdermott.io",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :pravatar_num, :admin, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(text, path, page) 
    active_class = text == page ? 'active' : ''
    link_to text, path, class: "nav-link " + active_class
  end
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/new.html.erb
<% provide(:page, 'Contact') %>
<div class="container">
  <h1>Contact Form</h1>
  <%= form_for @contact do |f| %>
    <div class="col-md-6">
      <%= f.label :name %></br>
      <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :email %></br>
      <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area", 
            placeholder: "Send me a message"%></br>

      <div class= "d-none">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>

      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<% provide(:page, 'Home') %>
<!-- <button type='button'
	class='btn btn-lg btn-danger'
	data-bs-toggle='popover'
	title='Popover title'
	data-bs-content='Amazing content, right?'>
	Click to toggle popover!
</button> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page) %> | Mark Test App</title> 
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <% if Rails.env.development? %>
      <%= javascript_include_tag "hotwire-livereload", defer: true %>
    <% end %>
  </head>

  <body>
    
    <%= render 'layouts/shared/header' %>
    <div class="container py-4">
      <div class="p-5 mb-4 bg-light rounded-3 static-page">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/shared/footer' %>
    
   <div></div> 

  </body>
</html>

app/views/layouts/shared/_header.html.erb
<% page = yield(:page) %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Test App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= nav_link('Home', root_path, page) %>
        </li>
        <li class="nav-item">
          <%= nav_link('About', about_path, page) %>
        </li>
        <li class="nav-item">
          <%= nav_link('Users', users_path, page) %>
        </li>
        <li class="nav-item">
          <%= nav_link('Help', help_path, page) %>
        </li>
        <li class="nav-item">
          <%= nav_link('Contact', contact_path, page) %>
        </li>
        <li class="nav-item">
          <a class="nav-link">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/shared/_static_page.html.erb
      <h1><%= yield(:page) %></h1>
      <p class="col-md-8"><%= yield :bodycopy %></p>
      <button class="btn btn-primary btn-lg" type="button">Example button</button>

app/views/static_pages/about.html.erb
<% provide(:page, 'About') %>
<% content_for :bodycopy do %>
Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
<% end %>

<%= render 'layouts/shared/static_page' %>

app/views/static_pages/help.html.erb
<% provide(:page, 'Help') %>
<% content_for :bodycopy do %>
Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.
<% end %>

<%= render 'layouts/shared/static_page' %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :pravatar_num, class: "form-label" %>
    <%= form.text_field :pravatar_num, class: "form-control" %>
  </div>

  <div class="form-check">
    <%= form.label :admin, class: "form-check-label" %>
    <%= form.check_box :admin, class: "form-check-input" %>
  </div>

  <div>
    <%= form.label "Password", class: "form-label" %>
    <%= form.password_field :password_digest, value: user.password_digest, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary my-4" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Pravatar #:</strong>
    <%= user.pravatar_num %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= user.admin %>
  </p>

</div>

app/views/users/edit.html.erb
<% provide(:page, 'Users') %>
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<% provide(:page, 'Users') %>
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <div class="user">
      <img class="user-page-avatar" src="https://i.pravatar.cc/100?img=<%= user.pravatar_num %>">
      <h2><%= user.name %></h2>
      <p>
        <%= link_to "Show this user", user, class: "btn btn-primary btn-lg" %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "Create a new user", new_user_path, class: "btn btn-primary btn-lg" %>

app/views/users/new.html.erb
<% provide(:page, 'Users') %>
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<% provide(:page, 'Users') %>
<p style="color: green"><%= notice %></p>

<img class="user-page-avatar" src="https://i.pravatar.cc/300?img=<%= @user.pravatar_num %>">
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user), class: "btn btn-primary btn-lg" %>
  <%= button_to "Destroy this user", @user, method: :delete, class: "btn btn-danger btn-lg" %>
  <%= link_to "Back to users", users_path %>
</div>